# version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/app
      - .:/var/www/html
      - ./docker/apache/apache.conf:/etc/apache2/sites-available/000-default.conf 
      - .env:/var/www/html/.env
    environment:
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    networks:
      - packtrack_network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_HOST=${DB_HOST}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - packtrack_network

networks:
  packtrack_network:
    name: packtrack_network
    driver: bridge

volumes:
  mysql_data:
